default: &default
  adapter: postgresql
  encoding: utf8
  charset: utf8
  pool: 5
  username: postgres
  password: postgres
  host: localhost
  port: 5432

development:
  <<: *default
  database: change_contact_development

production:
  <<: *default
  database: change_contact_production 

test:
  <<: *default
  database: change_contact_test
