# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ee44c31da53c434402f203222ce820a37e5e7fcbeb95a92c5fae4ca1552f5b1f21820b8a936371e25e751f2f74e5b8ef5197e934c61fdfde4e63ccf5d3c06f1

test:
  secret_key_base: 7338e23ea3ae3ea7521be14e1f2b9d60bf60da5b3f5177368cc9b1bdd4d68ba26e51a419f28643290ad03b208db65fc4fc05ae7cb3519720085b271c2fda4259

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
